In [1]:
import numpy as np
a=np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [11]:
a=np.random.randint(1,10,3)
a

array([5, 3, 6])

In [14]:
a=np.random.rand(5)
a


array([0.19236009, 0.60651476, 0.80057838, 0.73220095, 0.87616909])

In [17]:
a=np.random.randn(5)
a

array([ 0.34479189,  0.59672958,  1.28157286,  1.76270347, -0.75779113])

In [18]:
a=np.random.randint(1,50,12)
a

array([13, 42, 39, 12, 20, 30, 41, 26, 36, 16, 32, 29])

In [19]:
a.shape

(12,)

In [20]:
a=a.reshape(2,6)
a


array([[13, 42, 39, 12, 20, 30],
       [41, 26, 36, 16, 32, 29]])

In [21]:
a=a.reshape(6,2)
a


array([[13, 42],
       [39, 12],
       [20, 30],
       [41, 26],
       [36, 16],
       [32, 29]])

In [23]:
a=a.reshape(4,3)
a

array([[13, 42, 39],
       [12, 20, 30],
       [41, 26, 36],
       [16, 32, 29]])

In [24]:
a=a.reshape(3,4)
a


array([[13, 42, 39, 12],
       [20, 30, 41, 26],
       [36, 16, 32, 29]])

In [25]:
a=a.reshape(5,3)
a

ValueError: cannot reshape array of size 12 into shape (5,3)

In [26]:
a=a.reshape(-1,4)
a

array([[13, 42, 39, 12],
       [20, 30, 41, 26],
       [36, 16, 32, 29]])

In [30]:
np.random.seed(5)
a=np.random.randint(1,100,10)
a

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8])

In [31]:
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6]
b[:]=0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [33]:
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [34]:
b

array([0, 0, 0])

In [35]:
#conditional selection 
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
a>10


array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [37]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [39]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [40]:
a[a%2==0]


array([ 2,  4,  6,  8, 10, 12, 14])

In [42]:
a=list=[1,2,3,4]
print(a*2)


[1, 2, 3, 4, 1, 2, 3, 4]


In [45]:
list=[10,20,30]
array=np.array(list)
print((array*2))


[20 40 60]


In [48]:
list1=[5,6,7,8]
b=np.array(list1).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [52]:
list=[10,20,30,40]
a=np.array(list).reshape(2,2)
print(a)


[[10 20]
 [30 40]]


In [53]:
a+b

array([[15, 26],
       [37, 48]])

In [54]:
b-a

array([[ -5, -14],
       [-23, -32]])

In [55]:
a-b

array([[ 5, 14],
       [23, 32]])

In [56]:
a=np.array([10,20,30,40,50])
np.min(a)

10

In [57]:
np.max(a)

50

In [58]:
np.argmin(a)

0

In [59]:
np.argmax(a)

4

In [60]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [61]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [62]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [64]:
a=np.array([10,20,30,40,50,10,20,30,40])
np.unique(a,return_index = True , return_counts =True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 4], dtype=int64),
 array([2, 2, 2, 2, 1], dtype=int64))

In [66]:
a=np.array([10,20,30])
b=np.array([40,50,60])
a

array([10, 20, 30])

In [67]:
b

array([40, 50, 60])

In [68]:
np.hstack((a,b))

array([10, 20, 30, 40, 50, 60])

In [69]:
np.vstack((a,b))

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
# Q.1 = Write statement to import numpy ? 

import numpy as np

In [2]:
# Q.2 = Create an array using numpy ? 
import numpy as np
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [5]:
# Q.3 = Create an array of 10 random integers ?

import numpy as np
a=np.random.randint(1,20,10)
a

array([11,  9,  6, 17, 14,  7,  7,  2,  4, 14])

In [8]:
# Q.4 = Create an array of elements from  10-20? 

import numpy as np
a = np.arange(10, 21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
# Q.5 = Create an array which contains value 5 , 10 times ? 

import  numpy as np 
a = np.ones(10)*5
a


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [19]:
# Q.6 = Create a one dimensional array and convert that into 3*3 matrix ? 

import numpy as np
list=[10,20,30,40,50,60,70,80,90]
a=np.array(list).reshape(3,3)
a


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [20]:
# Q.8 = Concatenate 2D array horizontally and vertically ? 

a=np.array([10,20,30])
b=np.array([40,50,60])
a


array([10, 20, 30])

In [21]:
b

array([40, 50, 60])

In [23]:
np.hstack((a,b))

array([10, 20, 30, 40, 50, 60])

In [24]:
np.vstack((a,b))

array([[10, 20, 30],
       [40, 50, 60]])

In [34]:
# Q.7 = Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ? 
a=np.array([10,20,30,40])
b=np.array([60,70,80,90])
a

array([10, 20, 30, 40])

In [37]:
b

array([60, 70, 80, 90])

In [ ]:
a=a.diag(

In [1]:
import pandas as pd


In [2]:
a=pd.Series([1,2,45,67,86])
a


0     1
1     2
2    45
3    67
4    86
dtype: int64

In [3]:
type(a)

pandas.core.series.Series

In [6]:
a = {
    "Emp_Id" : [1,2,3,4,5,6,7,80]   ,
    "Name"   :['Sam','Rahul','Gorav','Aniket','Anjali','Ria','Muskan','Harsh'],
    "Department" :['IT','HR','Sales', 'IT','IT','Sales','IT','HR'],
    "Salary"   :[25000,27000,29000,31000,30000,39000,45000,28500],
    "Working_hours"  : [8,9,7,6,8,9,7,6]
}

In [7]:
type(a)

dict

In [8]:
df=pd.DataFrame(a)
df

Emp_Id    Name Department  Salary  Working_hours
0       1     Sam         IT   25000              8
1       2   Rahul         HR   27000              9
2       3   Gorav      Sales   29000              7
3       4  Aniket         IT   31000              6
4       5  Anjali         IT   30000              8
5       6     Ria      Sales   39000              9
6       7  Muskan         IT   45000              7
7      80   Harsh         HR   28500              6

In [9]:
df.head(5)

Emp_Id    Name Department  Salary  Working_hours
0       1     Sam         IT   25000              8
1       2   Rahul         HR   27000              9
2       3   Gorav      Sales   29000              7
3       4  Aniket         IT   31000              6
4       5  Anjali         IT   30000              8

In [10]:
df.head(1)

Emp_Id Name Department  Salary  Working_hours
0       1  Sam         IT   25000              8

In [11]:
df.tail(0)

Empty DataFrame
Columns: [Emp_Id, Name, Department, Salary, Working_hours]
Index: []

In [12]:
df.tail(1)

Emp_Id   Name Department  Salary  Working_hours
7      80  Harsh         HR   28500              6

In [13]:
df.tail(5)

Emp_Id    Name Department  Salary  Working_hours
3       4  Aniket         IT   31000              6
4       5  Anjali         IT   30000              8
5       6     Ria      Sales   39000              9
6       7  Muskan         IT   45000              7
7      80   Harsh         HR   28500              6

In [14]:
df.sample(3)


Emp_Id    Name Department  Salary  Working_hours
0       1     Sam         IT   25000              8
3       4  Aniket         IT   31000              6
7      80   Harsh         HR   28500              6

In [16]:
#how to export our data...
df.to_csv("C:\\Users\\Admin\\Desktop\\python advance (panda)\\Emp_info.csv")

In [18]:
df=pd.DataFrame(a)
df

Emp_Id    Name Department  Salary  Working_hours
0       1     Sam         IT   25000              8
1       2   Rahul         HR   27000              9
2       3   Gorav      Sales   29000              7
3       4  Aniket         IT   31000              6
4       5  Anjali         IT   30000              8
5       6     Ria      Sales   39000              9
6       7  Muskan         IT   45000              7
7      80   Harsh         HR   28500              6

In [1]:
print("hello")

hello


In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("C:\\Users\\Admin\\Desktop\\python advance (panda)\\covid_toy.csv")

In [4]:
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [5]:
df.tail(2)

age  gender  fever   cough     city has_covid
98    5  Female   98.0  Strong   Mumbai        No
99   10  Female   98.0  Strong  Kolkata       Yes

In [6]:
df = pd.read_csv("C:\\Users\\Admin\\Desktop\\python advance (panda)\\placement.csv")

In [7]:
df.head(5)

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [8]:
df


cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [9]:
df.tail()

cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [10]:
df.tail()

cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [11]:
df.sample()

cgpa  resume_score  placed
57  6.34          7.21       0

In [12]:
df.describe()

cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64  
dtypes: float64(2), int64(1)
memory usage: 2.5 KB


In [14]:
top_left_corner_df = df.iloc[:5 , :3] #iloc
top_left_corner_df

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [15]:
s = df.axes
s

[RangeIndex(start=0, stop=100, step=1),
 Index(['cgpa', 'resume_score', 'placed'], dtype='object')]

In [16]:
p = df.dtypes
p

cgpa            float64
resume_score    float64
placed            int64
dtype: object

In [17]:
b = df.empty
b


False

In [18]:
i = df.ndim
i

2

In [19]:
t = df.shape
t

(100, 3)

In [20]:
t = df.size
t

300

In [21]:
a=df.values
a

array([[8.14, 6.52, 1.  ],
       [6.17, 5.17, 0.  ],
       [8.27, 8.86, 1.  ],
       [6.88, 7.27, 1.  ],
       [7.52, 7.3 , 1.  ],
       [8.77, 6.19, 1.  ],
       [5.34, 7.09, 0.  ],
       [6.56, 6.29, 0.  ],
       [6.32, 6.71, 0.  ],
       [7.69, 7.12, 1.  ],
       [6.18, 6.35, 0.  ],
       [5.44, 6.54, 0.  ],
       [6.09, 7.01, 0.  ],
       [8.5 , 5.09, 1.  ],
       [7.51, 6.25, 1.  ],
       [8.88, 5.93, 1.  ],
       [8.04, 7.64, 1.  ],
       [7.81, 8.71, 1.  ],
       [5.94, 5.88, 0.  ],
       [6.75, 8.11, 1.  ],
       [5.8 , 8.06, 0.  ],
       [6.53, 7.64, 0.  ],
       [6.16, 5.77, 0.  ],
       [6.05, 7.13, 0.  ],
       [8.22, 6.18, 1.  ],
       [7.76, 5.68, 1.  ],
       [6.27, 6.47, 0.  ],
       [5.51, 6.15, 0.  ],
       [7.46, 7.67, 1.  ],
       [6.19, 7.3 , 0.  ],
       [7.36, 7.15, 1.  ],
       [5.92, 7.02, 0.  ],
       [5.87, 7.96, 0.  ],
       [8.43, 7.73, 1.  ],
       [8.87, 7.19, 1.  ],
       [8.07, 7.48, 1.  ],
       [8.16, 7.56, 1.  ],
 

In [22]:
df = df.copy()

In [23]:
p = df.sort_values(by= 'resume_score')
p

cgpa  resume_score  placed
94  8.01          4.95       1
87  5.62          5.05       0
13  8.50          5.09       1
41  8.68          5.15       1
1   6.17          5.17       0
..   ...           ...     ...
17  7.81          8.71       1
38  6.00          8.72       0
65  6.04          8.75       0
2   8.27          8.86       1
69  8.06          9.06       1

[100 rows x 3 columns]

In [24]:
#type conversion 
x = df.astype(int)
x

cgpa  resume_score  placed
0      8             6       1
1      6             5       0
2      8             8       1
3      6             7       1
4      7             7       1
..   ...           ...     ...
95     6             6       0
96     8             7       1
97     6             7       0
98     8             5       1
99     6             6       0

[100 rows x 3 columns]

In [26]:
x = df.astype(float)
x

cgpa  resume_score  placed
0   8.14          6.52     1.0
1   6.17          5.17     0.0
2   8.27          8.86     1.0
3   6.88          7.27     1.0
4   7.52          7.30     1.0
..   ...           ...     ...
95  6.33          6.38     0.0
96  8.23          7.76     1.0
97  6.65          7.78     0.0
98  8.14          5.63     1.0
99  6.09          6.61     0.0

[100 rows x 3 columns]

In [27]:
x=df['cgpa'].astype(int)
x

0     8
1     6
2     8
3     6
4     7
     ..
95    6
96    8
97    6
98    8
99    6
Name: cgpa, Length: 100, dtype: int32

In [28]:
t=df.add(4)
t

cgpa  resume_score  placed
0   12.14         10.52       5
1   10.17          9.17       4
2   12.27         12.86       5
3   10.88         11.27       5
4   11.52         11.30       5
..    ...           ...     ...
95  10.33         10.38       4
96  12.23         11.76       5
97  10.65         11.78       4
98  12.14          9.63       5
99  10.09         10.61       4

[100 rows x 3 columns]

In [1]:
import numpy as np


In [3]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [8]:
a=np.random.randint(1,10,10)
a

array([6, 5, 7, 1, 2, 6, 6, 3, 9, 6])

In [12]:
a=np.diag([1])
a

array([[1]])

In [14]:
a=np.random.rand(5)
a

array([0.77668389, 0.59459346, 0.20056907, 0.25544178, 0.44293817])

In [18]:
a.shape
a

array([0.77668389, 0.59459346, 0.20056907, 0.25544178, 0.44293817])

In [20]:
a=np.array([10,20,30])
a

array([10, 20, 30])

In [21]:
a.shape

(3,)

In [22]:
a.size

3

In [24]:
a=np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
a.shape


(9,)

In [32]:
a=a.reshape(3,3
           )
a

AttributeError: 'builtin_function_or_method' object has no attribute 'reshape'

In [34]:
b=np.array([1,2,3,4,5,6])
b

array([1, 2, 3, 4, 5, 6])

In [35]:
b.shape

(6,)

In [36]:
b=b.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
b=b.reshape(1,6)
b

array([[1, 2, 3, 4, 5, 6]])

In [53]:
a=np.array([13,20,30,40,50,60])
b=np.array([60,50,40,30,20,10])
a


array([13, 20, 30, 40, 50, 60])

In [46]:
a

array([10, 20, 30, 40, 50, 60])

In [45]:
b

array([60, 50, 40, 30, 20, 10])

In [47]:
a+b

array([70, 70, 70, 70, 70, 70])

In [48]:
b-a

array([ 50,  30,  10, -10, -30, -50])

In [51]:
a<=10

array([ True, False, False, False, False, False])

In [54]:
a=[a%2==0]
a

[array([False,  True,  True,  True,  True,  True])]

In [58]:
np.max(a)


True

In [61]:
c=np.array([10,20,30,40,50,60])
c

array([10, 20, 30, 40, 50, 60])

In [72]:
np.min(c)

10

In [73]:


np.max(c)
c

10

In [77]:
a=np.array([1,2,3])
a
np.max(a)

3

In [81]:
np.argmax(a)

2

In [85]:
d=np.array([10,20,30,40,50,60])
e=np.array([90,80,70,12,14,15])
np.hstack((d,e))
np.vstack((d,e))

array([[10, 20, 30, 40, 50, 60],
       [90, 80, 70, 12, 14, 15]])

NameError: name 'd' is not defined

In [86]:
import pandas as pd

In [89]:
g = {
    "Emp_Id" : [1,2,3,4,5,6,7,80]   ,
    "Name"   :['Sam','Rahul','Gorav','Aniket','Anjali','Ria','Muskan','Harsh'],
    "Department" :['IT','HR','Sales', 'IT','IT','Sales','IT','HR'],
    "Salary"   :[25000,27000,29000,31000,30000,39000,45000,28500],
    "Working_hours"  : [8,9,7,6,8,9,7,6]
}

In [90]:
df=pd.DataFrame(g)
df

Emp_Id    Name Department  Salary  Working_hours
0       1     Sam         IT   25000              8
1       2   Rahul         HR   27000              9
2       3   Gorav      Sales   29000              7
3       4  Aniket         IT   31000              6
4       5  Anjali         IT   30000              8
5       6     Ria      Sales   39000              9
6       7  Muskan         IT   45000              7
7      80   Harsh         HR   28500              6

In [91]:
df.head(2)

Emp_Id   Name Department  Salary  Working_hours
0       1    Sam         IT   25000              8
1       2  Rahul         HR   27000              9

In [93]:
df.tail(2)

Emp_Id    Name Department  Salary  Working_hours
6       7  Muskan         IT   45000              7
7      80   Harsh         HR   28500              6

In [95]:
df = pd.read_csv("C:\\Users\\Admin\\Desktop\\python advance (panda)\\titanic.csv")

In [96]:
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [97]:
df.tail()

PassengerId  Survived  Pclass                          Name     Sex  \
413         1305         0       3            Spector, Mr. Woolf    male   
414         1306         1       1  Oliva y Ocana, Dona. Fermina  female   
415         1307         0       3  Saether, Mr. Simon Sivertsen    male   
416         1308         0       3           Ware, Mr. Frederick    male   
417         1309         0       3      Peter, Master. Michael J    male   

      Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
413   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  39.0      0      0            PC 17758  108.9000  C105        C  
415  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416   NaN      0      0              359309    8.0500   NaN        S  
417   NaN      1      1                2668   22.3583   NaN        C

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB


In [99]:
df.sample()

PassengerId  Survived  Pclass                Name   Sex  Age  SibSp  \
413         1305         0       3  Spector, Mr. Woolf  male  NaN      0   

     Parch     Ticket  Fare Cabin Embarked  
413      0  A.5. 3236  8.05   NaN        S

In [100]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   418.000000  418.000000  418.000000  332.000000  418.000000   
mean   1100.500000    0.363636    2.265550   30.272590    0.447368   
std     120.810458    0.481622    0.841838   14.181209    0.896760   
min     892.000000    0.000000    1.000000    0.170000    0.000000   
25%     996.250000    0.000000    1.000000   21.000000    0.000000   
50%    1100.500000    0.000000    3.000000   27.000000    0.000000   
75%    1204.750000    1.000000    3.000000   39.000000    1.000000   
max    1309.000000    1.000000    3.000000   76.000000    8.000000   

            Parch        Fare  
count  418.000000  417.000000  
mean     0.392344   35.627188  
std      0.981429   55.907576  
min      0.000000    0.000000  
25%      0.000000    7.895800  
50%      0.000000   14.454200  
75%      0.000000   31.500000  
max      9.000000  512.329200

In [101]:
a=df.empty
a

False

In [106]:
df = pd.read_csv("C:\\Users\\Admin\\Desktop\\python advance (panda)\\tips.csv")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [107]:
df.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [108]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB
